/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./../src/pages/AboutPage/AboutPage.vue')['default']
    AppointmentPage: typeof import('./../src/pages/AppointmentPage/AppointmentPage.vue')['default']
    CInformationCard: typeof import('./../src/components/CInformationCard.vue')['default']
    ContactsPage: typeof import('./../src/pages/ContactsPage/ContactsPage.vue')['default']
    DefaultFooter: typeof import('./../src/layouts/DefaultFooter/DefaultFooter.vue')['default']
    DefaultLayout: typeof import('./../src/layouts/DefaultLayout/DefaultLayout.vue')['default']
    MainPage: typeof import('./../src/pages/MainPage/MainPage.vue')['default']
    MainPageAbout: typeof import('./../src/pages/MainPage/MainPageAbout/MainPageAbout.vue')['default']
    MainPageBanner: typeof import('./../src/pages/MainPage/MainPageBanner/MainPageBanner.vue')['default']
    MainPageCarousel: typeof import('./../src/pages/MainPage/MainPageCarousel/MainPageCarousel.vue')['default']
    MainPageContacts: typeof import('./../src/pages/MainPage/MainPageContacts/MainPageContacts.vue')['default']
    MainPageOperations: typeof import('./../src/pages/MainPage/MainPageOperations/MainPageOperations.vue')['default']
    NotFoundPage: typeof import('./../src/pages/NotFoundPage/NotFoundPage.vue')['default']
    PlasticBodyPage: typeof import('./../src/pages/PlasticPage/PlasticBodyPage/PlasticBodyPage.vue')['default']
    PlasticFacePage: typeof import('./../src/pages/PlasticPage/PlasticFacePage/PlasticFacePage.vue')['default']
    PlasticMamoPage: typeof import('./../src/pages/PlasticPage/PlasticMamoPage/PlasticMamoPage.vue')['default']
    PlasticPage: typeof import('./../src/pages/PlasticPage/PlasticPage.vue')['default']
    PortfolioPage: typeof import('./../src/pages/PortfolioPage/PortfolioPage.vue')['default']
    PrepareOperationPage: typeof import('./../src/pages/PlasticPage/PrepareOperationPage/PrepareOperationPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
